### PR TITLE
Delete makeRelease.py

### PR DESCRIPTION
**Pull request by jwodder**
The script has been moved to dand/dandi-cli in dandi/dandi-cli#276 as requested in dandi/dandi-cli#273.

### CODE REVIEW

**Comment by yarikoptic** [comment]
workflow(s) need fixup to account for it

**Comment by jwodder** [comment]
@yarikoptic @satra I think the workflow might be obsolete at this point and should probably be just deleted.  For one thing, it also refers to a `scripts/models.py` file that no longer exists.

**Comment by satra** [comment]
sounds good to me.

**Comment by jwodder** [comment]
Workflow deleted.

**Pull request merged**
